---
title: "Cleaning_National_Park"
author: "Neda Safari"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(dplyr)
library(tidyverse)

NPVisit<- read_csv("../data/All National Parks Visitation 1904-2016.csv")%>%
  mutate( gnis_id= `Gnis Id`)

locationNP<- read_csv("../data/locations.csv")%>%
  mutate(`Gnis Id` = gnis_id)

NPVisit<-NPVisit%>%
  dplyr::select(gnis_id, Parkname:YearRaw)%>%
  drop_na()%>%
  filter(YearRaw %in% c("2007", "2008", "2009", "2010", "2011","2012", "2013", "2014", "2015", "2016"))%>%
  mutate(gnis_id= as.character(gnis_id))

joind_loc_visit<- left_join(NPVisit, locationNP, by=c("gnis_id"= "gnis_id"))
total_park_visit<- joind_loc_visit%>%
  group_by(Parkname, gnis_id)%>%
  summarise(Count = n(), TotalValue = sum(Visitors))%>%
  ungroup()

joind_total_loc<- left_join(total_park_visit, locationNP, by= c("gnis_id"= "gnis_id"))

write.csv(joind_total_loc, "../data/NPVisitCleaned.csv")
write.csv(joind_loc_visit, "../data/NPVisitbyYearCleaned.csv")
```

